<?php

$mainDomain = env('MAIN_DOMAIN', 'ygtlabs.co');
$allowedDomains = env('ALLOWED_DOMAINS', "*.$mainDomain");

return [
    'headers' => [
        'Content-Security-Policy' => [
            'default-src' => ["'self'", "https:", "http:", "data:", "ws:", "wss:"],
            'script-src' => [
                "'self'",
                "'unsafe-inline'",
                "'unsafe-eval'",
                "'wasm-unsafe-eval'",
                "'inline-speculation-rules'",
                "https://fonts.bunny.net",
                "https://fonts.googleapis.com",
                "chrome-extension:",
                "https://*.google.com",
                "https://*.facebook.com",
                "https://*.github.com",
                "https://$allowedDomains",
                "blob:",
            ],
            'style-src' => [
                "'self'",
                "'unsafe-inline'",
                "https://fonts.bunny.net",
                "https://fonts.googleapis.com",
                "https://$allowedDomains",
            ],
            'font-src' => [
                "'self'",
                "https://fonts.bunny.net",
                "https://fonts.gstatic.com",
                "data:",
            ],
            'img-src' => [
                "'self'",
                "data:",
                "blob:",
                "https:",
                "http:",
                "https://*.googleusercontent.com",
                "https://*.githubusercontent.com",
                "https://graph.facebook.com",
                "https://$allowedDomains",
            ],
            'connect-src' => [
                "'self'",
                "wss:",
                "ws:",
                "https:",
                "http:",
                "https://*.google.com",
                "https://*.facebook.com",
                "https://*.github.com",
                "https://$allowedDomains",
                "chrome-extension:",
            ],
            'frame-src' => [
                "'self'",
                "https:",
                "http:",
                "chrome-extension:",
            ],
            'media-src' => ["'self'", "https:", "http:", "data:", "blob:"],
            'object-src' => ["'none'"],
            'base-uri' => ["'self'"],
            'form-action' => ["'self'", "https:", "http:"],
            'worker-src' => ["'self'", "blob:", "https:", "http:"],
            'child-src' => ["'self'", "blob:", "https:", "http:"],
            'frame-ancestors' => ["'self'"],
        ],
        'X-Frame-Options' => 'SAMEORIGIN',
        'X-Content-Type-Options' => 'nosniff',
        'X-XSS-Protection' => '1; mode=block',
        'Referrer-Policy' => 'strict-origin-when-cross-origin',
        'Permissions-Policy' => 'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()',
    ],
]; 